#cmakedefine KDEPIMLIBS_VERSION_MAJOR @KDEPIMLIBS_VERSION_MAJOR@
#cmakedefine KDEPIMLIBS_VERSION_MINOR @KDEPIMLIBS_VERSION_MINOR@
#cmakedefine KDEPIMLIBS_VERSION_PATCH @KDEPIMLIBS_VERSION_PATCH@
#define KDEPIMLIBS_MAKE_VERSION( a,b,c ) (((a) << 16) | ((b) << 8) | (c))
#define KDEPIMLIBS_VERSION \
  KDEPIMLIBS_MAKE_VERSION(KDEPIMLIBS_VERSION_MAJOR,KDEPIMLIBS_VERSION_MINOR,KDEPIMLIBS_VERSION_PATCH)

#define KDEPIMLIBS_IS_VERSION(a,b,c) ( KDEPIMLIBS_VERSION >= KDEPIMLIBS_MAKE_VERSION(a,b,c) )

#cmakedefine KDEPIM_44_COMPAT @KDEPIM_44_COMPAT@